"""empty message

Revision ID: 089d77e7fb51
Revises: 7bee734c5616
Create Date: 2020-06-27 10:57:59.296951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '089d77e7fb51'
down_revision = '7bee734c5616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FaultTypes', sa.Column('is_active', sa.Boolean(),default=True, server_default='True', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('FaultTypes', 'is_active')
    # ### end Alembic commands ###
