"""empty message

Revision ID: 450cfd8a0eac
Revises: 
Create Date: 2020-06-28 20:02:05.809824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '450cfd8a0eac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='True', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ITSections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='True', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('FaultTypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fault_type', sa.String(), nullable=False),
    sa.Column('it_section', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='True', nullable=False),
    sa.ForeignKeyConstraint(['it_section'], ['ITSections.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Faults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fault_type', sa.Integer(), nullable=False),
    sa.Column('fault_description', sa.String(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Finished', 'New', 'UnderWrok', name='faultstatus'), server_default='New', nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['Branches.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['fault_type'], ['FaultTypes.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('FaultsAction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fault_id', sa.Integer(), nullable=False),
    sa.Column('action_taken', sa.String(), nullable=False),
    sa.Column('action_by', sa.Integer(), nullable=False),
    sa.Column('action_time', sa.DateTime(), nullable=False),
    sa.Column('current_status', sa.Integer(), nullable=False),
    sa.Column('new_status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['action_by'], ['ITSections.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['fault_id'], ['Faults.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FaultsAction')
    op.drop_table('Faults')
    op.drop_table('FaultTypes')
    op.drop_table('ITSections')
    op.drop_table('Branches')
    # ### end Alembic commands ###
